---
title: "Publications"
date: '`r format(Sys.time(), "%d %B, %Y")`'
---

```{r setup, include = F}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(knitr)
knitr::opts_chunk$set(echo = F)
knitr::opts_chunk$set(warning = F)
knitr::opts_chunk$set(message = F)
```


> Naithani Lab members are in bold. 

[Google Scholar](https://scholar.google.com/citations?hl=en&user=t1udHZoAAAAJ&view_op=list_works&gmla=ALUCkoXYuTmdZbYSUoXEtNNr0_3fm34RingQPYsSrxpkBgYENg6qzjz1oJOJ-UQ8JEMMDOgX2oL_GGYw0TJ6BSi0) | [ResearchGate](https://www.researchgate.net/profile/Kusum-Naithani) | [ORCID](https://orcid.org/0000-0003-2503-113X)


---


#### **Peer Reviewed**

1.  **St. Rose A.**, Xiao J., and **Naithani K.** (in review) Combined landscape complexity is a better indicator of ecosystem functions in forested ecosystems than physical or biological complexity alone. 

2. Kuhn E., Moreno-Garcia B., Reba M., **Naithani K.**, and Runkle B. R. K. (2025) Modeling rice leaf area index and canopy height in the U.S. Mid-South region. Agrosystems, Geosciences & Environment, agg2.70139. [doi: 10.1002/agg2.70139](https://acsess.onlinelibrary.wiley.com/doi/10.1002/agg2.70139)

3. **St. Rose A.**, and **Naithani K.** (2025) Unraveling the influence of structural complexity, environmental, and geographic factors on multi-trophic biodiversity in forested landscapes. Ecology and Evolution. Vol: 15 (2) e70907. [doi:10.1002/ece3.70907](https://onlinelibrary.wiley.com/doi/10.1002/ece3.70907)

4. Acharya R. S., Leslie T., Burke J., **Naithani K.**, Fitting E., Loftin K., and Joshi N. K. (2024) Sheep grazing influences the abundance, diversity, and community composition of wild bees and other insects in livestock pastures. Ecological Indicators, Vol: 162, 111839. [doi: 10.ECOLIND-31242R2](https://doi.org/10.1016/j.ecolind.2024.111839) 

5.  Syed M., Farmer M.C., **Naithani K.J.**, and Lacombe D. J. (2024) A problem with distance variables and alternatives for their use. Journal of Real Estate Research. [doi: 10.1080/08965803.2024.2325244](https://doi.org/10.1080/08965803.2024.2325244)

6. **Reavis M. L.**, Purcell L., Pereira A., and **Naithani K.** (2023) Effects of measurement methods and growing conditions on phenotypic expression of photosynthesis in diverse rice genotypes. Frontiers in Plant Science. Volume 14. [doi: 10.3389/fpls.2023.1106672](https://doi.org/10.3389/fpls.2023.1106672)

7. **Naithani K.**, Jones M., and Grayson K. (2022) Building communities of teaching practice and data-driven open education resources with NEON faculty mentoring networks. Ecosphere, 13(8): e4210. [doi: 10.1002/ecs2.4210](https://doi.org/10.1002/ecs2.4210)

8. SanClements M., Record S., Rose K., Donnelly A., Chong S., Duffy K., Hallmark A., Heffernan J., Mitchell J., Moore D., Naithani K., O’Reilly C., Sokol E., Weintraub S., Stack Whitney K., and Yang D. (2022) People, infrastructure, and data: A pathway to an inclusive and diverse ecological Network of Networks. Ecosphere, e4262. [doi: 10.1002/ecs2.4262](https://doi.org/10.1002/ecs2.4262)

9. **Sniegocki R.**, **Moon J. B.**, **Rutrough A.**, **Gireneus J.**, Seelan J. S. S., Weindorf D., Farmer M. C., and **Naithani K.** (2022) Recovery of soil microbial diversity and functions along a tropical montane forest disturbance gradient, Frontiers in Environmental Science, 10: 853686. [doi: 10.3389/fenvs.2022.853686](https://doi.org/10.3389/fenvs.2022.853686)

10. **Reavis M. L.**, Ahlen J., Rudek J., and **Naithani K.** (2022) Evaluating greenhouse gas emissions and climate mitigation goals of the global food and beverage sector. Frontiers in Sustainable Food Systems, 5:789499. [doi: 10.3389/fsufs.2021.789499](https://doi.org/10.3389/fsufs.2021.789499)

11. Nagy R. C. et al. (90 co-authors including **Naithani K.**, 2021) Harnessing the NEON data revolution to advance open environmental science with a diverse, inclusive, and data-capable community. Ecosphere, 12 (12): e03833. [doi:10.1002/ecs2.3833](https://doi.org/10.1002%2Fecs2.3833)

12. Qin C., Bartelme R., Chung A., Fairbanks D., Lin Y., Liptzin D., Muscarella C., **Naithani K.**, Peay K., Pellitier P., GSt. Rose A., Stanish L., Werbin Z., and Zhu K. (2021) From DNA sequences to microbial ecology: Wrangling NEON soil microbe data with the neonMicrobe R package. Ecosphere, 12(11): e03842. [doi: 10.1002/ecs2.3842](https://doi.org/10.1002%2Fecs2.3842)

13. Sanks K. M., Shaw J. B., and **Naithani K.** (2020) Field-based estimate of the sediment deficit in coastal Louisiana. JGR–Earth Surface. 125 (8) e2019JF005389. [doi: 10.1029/2019JF005389](https://doi.org/10.1029/2019JF005389).

14. Joshi N. K., **Naithani K.**, and Biddinger D. J. (2020) Nest modification protects immature stages of the Japanese orchard bee (Osmia cornifrons) from invasion of a cleptoparasitic mite pest. Insects, 11(1), 65. [doi: 10.3390/insects11010065](https://doi.org/10.3390/insects11010065)

15. Shaffer L. J., GKhadka K. K., Van Den Hoek J., and **Naithani K.J.** (2019) Human-elephant conflict: A review of management strategies and future directions. Frontiers in Ecology and Evolution, 6:235. [doi: 10.3389/fevo.2018.00235](https://doi.org/10.3389/fevo.2018.00235) 

16. **Moon J. B.**, Wardrop D. H., Smithwick E. A. H., and **Naithani K.J.** (2019) Fine-scale spatial homogenization of microbial habitats: a multivariate index of headwater wetland complex condition. Ecological Applications, 29(1), e0181. [doi: 10.1002/eap.1816](https://doi.org/10.1002/eap.1816)

17. **Mitra B.**, Mackay D. S., Cleary M. B., Pendall E., Ewers B. E., Kwon H., Cleary M. B., and **Naithani K.J.** (2018) Model – Data fusion approach to quantify evapotranspiration and net ecosystem exchange across the sagebrush ecosystem at different temporal resolutions. Ecohydrology, e1957. [doi: 10.1002/eco.1957](https://doi.org/10.1002/eco.1957)

18. Reed D., Ewers B. E., Pendall E., **Naithani K.J.**, Kwon H., and Kelly R. (2018) Biophysical factors and canopy coupling control ecosystem fluxes of sagebrush ecosystems. Rangeland Ecology and Management, 71(3): 309-317. [doi: 10.1016/j.rama.2018.01.003](https://doi.org/10.1016/j.rama.2018.01.003)

19. **Moon J. B.**, DeWitt T. H., Errend M. E., Bruins R. A., Kentula M. E., Chamberlain S. J., Fennessy M. S., and **Naithani K.J.** (2017) Model application niche analysis: Assessing the transferability and generalizability of ecological models. Ecosphere, 8(10): e01974. [doi: 10.1002/ecs2.1974](https://doi.org/10.1002%2Fecs2.1974)

20. Baldwin D., **Naithani K.J.**, and Lin H. (2017) Combined soil-terrain stratification for characterizing catchment-scale soil moisture variation. Geoderma, 285: 260–269. [doi: 10.1016/j.geoderma.2016.09.031](https://doi.org/10.1016/j.geoderma.2016.09.031)

21. Smithwick E. A. H., Baldwin D., and **Naithani K.J.** (2016) Quantifying spatial patterns of grass response to nutrient additions using empirical and neutral semivariogram models. PeerJ, 4: e2745. [doi: 10.7717/peerj.2745](https://doi.org/10.7717/peerj.2745)

22. Joshi N. K., Rajotte E. G., **Naithani K.J.**, Krawczyk G., and Hull L. A. (2016) Population dynamics and flight phenology model of codling moth differ between commercial and abandoned apple orchard ecosystems. Frontiers in Physiology, 7:408. [doi: 10.3389/fphys.2016.00408](https://doi.org/10.3389/fphys.2016.00408)
       
23.  **Moon J. B.**, Wardrop D. H., Bruns M. A. V., Miller R. M., and **Naithani K.J.** (2016) Land-use and land-cover effects on soil microbial community abundance and composition in headwater riparian wetlands. Soil Biology and Biochemistry, 97: 215 – 233. [doi: 10.1016/j.soilbio.2016.02.021](https://doi.org/10.1016/j.soilbio.2016.02.021)

24.  Cleary M. B., **Naithani K.**, Ewers B. E., and Pendall E. (2015) Upscaling CO<sub>2</sub> fluxes using leaf, soil and chamber measurements across successional growth stages in a sagebrush steppe ecosystem. Journal of Arid Environments. 12: 43–51. [doi: 10.1016/j.jaridenv.2015.05.013](https://doi.org/10.1016/j.jaridenv.2015.05.013)
       
25. **Naithani K.**, Ewers B. E., Adelman J. D., and Siemens D. H. (2014) Abiotic and biotic controls on spatial distribution and performance of a Boechera stricta population. Frontiers in Plant Science, 5: 348. [doi: 10.3389/fpls.2014.00348](https://doi.org/10.3389/fpls.2014.00348)
       
26. **Naithani K.**, Baldwin D., Gaines K., Lin H., and Eissenstat D. M. (2013) Spatial distribution of tree species governs the spatio–temporal interaction of leaf area index and soil moisture across a forested landscape. PLoS ONE, 8(3): e58704. [doi: 10.1371/journal.pone.0058704](https://doi.org/10.1371/journal.pone.0058704)
       
27. Biddinger D. J., Joshi N. K., Rajotte E. G., Halbrendt N. O., Pulig C., **Naithani K.J.**, and Vaughn M. (2013). An immunomarking method to determine the foraging patterns of Osmia cornifrons and resulting fruit set in a cherry orchard. Apidologie, 44 (6): 738–749. [doi: 10.1007/s13592-013-0221-x](https://link.springer.com/article/10.1007/s13592-013-0221-x)

28. **Naithani K.J.**, Ewers B. E., and Pendall E. (2012) Sapflux–scaled transpiration and stomatal conductance response to soil and atmospheric drought in a semi–arid sagebrush ecosystem. Journal of Hydrology, 464–465: 176–185. [doi: 10.1016/j.jhydrol.2012.07.008](https://doi.org/10.1016/j.jhydrol.2012.07.008)

29. Smithwick E. A. H., **Naithani K.J.**, Balser T. C., Romme W. H., and Turner M. G. (2012) Post–fire spatial patterns of soil nitrogen mineralization and microbial abundance. PLoS ONE, 7(11): e50597. [doi: 10.1371/journal.pone.0050597](https://doi.org/10.1371/journal.pone.0050597) 

30. Kwon H., Pendall E., Ewers B. E., Cleary M., and **Naithani K.** (2008) Spring drought regulates summer net ecosystem CO<sub>2</sub> exchange in a sagebrush steppe–ecosystem. Agricultural and Forest Meteorology, 148: 381–391. [doi: 10.1016/j.agrformet.2007.09.010](https://doi.org/10.1016/j.agrformet.2007.09.010)  


---


#### **Datasets**

31. **Reavis M. L.**, Purcell L., Pereira A., and **Naithani K.** (2023) Effects of Measurement Methods and Growing Conditions on Phenotypic Expression of Photosynthesis in Diverse Rice Genotypes. Dryad, Dataset, [doi: 10.5061/dryad.6wwpzgn22]()

32. **Naithani K.**,GSniegocki R., PMoon J. B., URutrough A., UGireneus J. (2022) Data: Recovery of soil microbial diversity and functions along a tropical montane forest disturbance gradient. Dryad, Dataset, [doi: 10.5061/dryad.0vt4b8h1t]() 

33. **Naithani K.**, Jones M, and Grayson K. (2022) Data: Building communities of teaching practice and data-driven open education resources with NEON faculty mentoring networks. Dryad, Dataset, [doi:10.5061/dryad.f1vhhmh03]()

34. **Naithani K.**, Jones M., and Grayson K. (2020) Using the QUBES platform and NEON faculty mentoring networks to build, adapt, and publish data-driven teaching resources. QUBES Educational Resources. [doi: 10.25334/PEJ1-HH75](https://qubeshub.org/publications/1387/1)

35. **Naithani K.** (2020) NEON Data in the Classroom: Quantifying Spatial Patterns. NEON Faculty Mentoring Network, QUBES Educational Resources. [doi: 10.25334/AJBF-AZ49](https://qubeshub.org/publications/1398/1)

36. **Naithani K.**, Jones M., and Grayson K. (2019) NEON data in the classroom: Using the QUBES platform and faculty mentoring networks to build, adapt, and publish data-driven teaching resources. QUBES Educational Resources. [doi: 10.25334/W83X -S558]()

37. **Moon J. B.**, Wardrop D. H., Smithwick E. A. H., and Naithani K. (2018) Data from: Fine-scale spatial homogenization of microbial habitats: a multivariate index of headwater wetland complex condition. Dryad, Dataset, [doi: 10.5061/dryad.4045sq6]() 


---


#### **Non Peer-Reviewed Publications**

38. Joshi N. K., **Naithani K.**, Hull L. A., Rajotte E. G., and Krawczyk G. (2011) Development of a Bayesian flight model for codling moth, Cydia pomonella (L.) in Pennsylvania apple orchards. Pennsylvania Fruit News, 91(5): 24–30.

39. **Naithani K. (2009)** Spatial and temporal controls on population and flux processes in steppe ecosystems. Doctoral dissertation, University of Wyoming, Laramie WY.

40. **Naithani K.** (2001) Alleviation of SO<sub>2</sub> toxicity in maize and sunflower plants using lime water. Master Thesis, G. B. P. University of Agriculture and Technology, Pantnagar, India. 

---


>These materials are not endorsed, approved, sponsored, or provided by or on behalf of the University of Arkansas, Fayetteville.


---
