---
title: "Lab Resources"
date: '`r format(Sys.time(), "%d %B, %Y")`'
---

```{r setup, include = F}
  if (!require("pacman")) install.packages("pacman")
  pacman::p_load(knitr)
  knitr::opts_chunk$set(echo = F)
  knitr::opts_chunk$set(warning = F)
  knitr::opts_chunk$set(message = F)
```

---


#### **Forms** 

[University of Arkansas GSIE](https://graduate-students.uark.edu/)

[Campus Map with Lactation Rooms and Accessible Points](https://campusmaps.uark.edu/?pnl_disp=N&accessible_pt=Y&id=2110#!ct/94027,94028,94029,94030) 

[Anthony Travel](https://travel.uark.edu/travel-arrangements/anthony-travel-agency.php)

[International Travel & Export Control](https://travel.uark.edu/travel-policy/international-travel.php)

[Travel Survival Guide](https://uark.sharepoint.com/sites/wdt/SitePages/Travel-Survival-Guide.aspx)


---


#### **Lab Reading List**

Reading and synthesizing information is essential to succed in graduate school. Below is the recommended reading list to start developing common knowledge base as a productive lab group member.  


---


**Foundational papers**


1. Allen, C. R., D. G. Angeler, G. S. Cumming, C. Folke, D. Twidwell, and D. R. Uden. 2016. Quantifying spatial resilience. Journal of Applied Ecology 53:625–635.

2. Allen, C. R., D. G. Angeler, A. S. Garmestani, L. H. Gunderson, and C. S. Holling. 2014. Panarchy: Theory and application. Ecosystems 17:578–589.

3. Allen, C. R., D. G. Angeler, A. Garmestani, C. P. Roberts, S. M. Sundstrom, D. Twidwell, and D. R. Uden. 2022. Applications of Spatial Regimes. Page 136 in L. H. Gunderson, C. R. Allen, and A. Garmestani, editors. Applied Panarchy: Applications and Diffusion Across Disciplines. Island Press.

4. Allen, T. F., and T. W. Hoekstra. 2015. Toward a unified ecology. Columbia University Press.
Angeler, D. G., H. B. Fried-Petersen, C. R. Allen, A. Garmestani, D. Twidwell, W.-C. Chuang, V. M. Donovan, T. Eason, C. P. Roberts, S. M. Sundstrom, and others. 2019. Adaptive capacity in ecosystems. Advances in ecological research 60:1–24.

5. Feyerabend, P. K. 1978. Science in a free society. London: NLB.

6. Garmestani, A., D. Twidwell, D. G. Angeler, S. Sundstrom, C. Barichievy, B. C. Chaffin, T. Eason, N. Graham, D. Granholm, L. Gunderson, and others. 2020. Panarchy: Opportunities and challenges for ecosystem management. Frontiers in Ecology and the Environment 18:576–583.

7. Gunderson, L. H. 2000. Ecological resilience—in theory and application. Annual review of ecology and systematics 31:425–439.

8. Gunderson, L. H., C. R. Allen, and A. Garmestani. 2022. Applied panarchy: Applications and diffusion across disciplines. Island Press.

9. Hacking, I. 2006. The emergence of probability: A philosophical study of early ideas about probability, induction and statistical inference. Cambridge University Press.

10. Hiers, J. K., S. T. Jackson, R. J. Hobbs, E. S. Bernhardt, and L. E. Valentine. 2016. The precision problem in conservation and restoration. Trends in Ecology & Evolution 31:820–830.

11. Hillebrand, H., I. Donohue, W. S. Harpole, D. Hodapp, M. Kucera, A. M. Lewandowska, J. Merder, J. M. Montoya, and J. A. Freund. 2020. Thresholds for ecological responses to global change do not emerge from empirical data. Nature Ecology & Evolution 4:1502–1509.

12. Holling, C. S. 1973. Resilience and stability of ecological systems. Annual review of ecology and systematics 4:1–23.

13. Johnstone, J. F., C. D. Allen, J. F. Franklin, L. E. Frelich, B. J. Harvey, P. E. Higuera, M. C. Mack, R. K. Meentemeyer, M. R. Metz, G. L. Perry, and others. 2016. Changing disturbance regimes, ecological memory, and forest resilience. Frontiers in Ecology and the Environment 14:369–378.

14. Levin, S. A. 1992. The problem of pattern and scale in ecology: The robert h. MacArthur award lecture. Ecology 73:1943–1967.

15. Mitchell, M. 2009. Complexity: A guided tour. Oxford university press.

16. Nash, K. L., C. R. Allen, D. G. Angeler, C. Barichievy, T. Eason, A. S. Garmestani, N. A. Graham, D. Granholm, M. Knutson, R. J. Nelson, and others. 2014. Discontinuities, cross-scale patterns, and the organization of ecosystems. Ecology 95:654–667.

17. Naugle, D. E., B. W. Allred, M. O. Jones, D. Twidwell, and J. D. Maestas. 2020. Coproducing science to inform working lands: The next frontier in nature conservation. BioScience 70:90–96.

18. Roberts, C. P., C. R. Allen, D. G. Angeler, and D. Twidwell. 2019. Shifting avian spatial regimes in a changing climate. Nature Climate Change 9:562–566.

19. Roberts, C. P., D. R. Uden, S. M. Cady, B. Allred, S. Fuhlendorf, M. O. Jones, J. D. Maestas, D. Naugle, A. C. Olsen, J. Smith, and others. 2022. Tracking spatial regimes as an early warning for a species of conservation concern. Ecological Applications:doi:10.1002/eap.2480.

20. Scheffer, M., and S. R. Carpenter. 2003. Catastrophic regime shifts in ecosystems: Linking theory to observation. Trends in ecology & evolution 18:648–656.

21. Seidl, R., and M. G. Turner. 2022. Post-disturbance reorganization of forest ecosystems in a changing world. Proceedings of the National Academy of Sciences 119:e2202190119.

22. Spanbauer, T. L., C. R. Allen, D. G. Angeler, T. Eason, S. C. Fritz, A. S. Garmestani, K. L. Nash, and J. R. Stone. 2014. Prolonged instability prior to a regime shift. PLoS One 9:e108936.
Steffen, W., K. Richardson, J. Rockström, S. E. Cornell, I. Fetzer, E. M. Bennett, R. Biggs, S. R. Carpenter, W. De Vries, C. A. De Wit, and others. 2015. Planetary boundaries: Guiding human development on a changing planet. Science 347:1259855.

23. Turner, M. G. 2010. Disturbance and landscape dynamics in a changing world. Ecology 91:2833–2849.
Turner, M. G., R. V. O’Neill, R. H. Gardner, and B. T. Milne. 1989. Effects of changing spatial scale on the analysis of landscape pattern. Landscape ecology 3:153–162.


---


>These materials are not endorsed, approved, sponsored, or provided by or on behalf of the University of Arkansas, Fayetteville.


---
